#!/usr/bin/python
# -*- coding: UTF-8 -*-

from os import system, name
import itertools
import threading
import time
import sys
import datetime
from base64 import b64decode,b64encode
from datetime import date

expirydate = datetime.date(2021, 10, 31)
#expirydate = datetime.date(2021, 10, 4)
today=date.today()
def hero():

    def chalo():
        done = False
        #here is the animation
        def animate():
            for c in itertools.cycle(['|', '/', '-', '\\']) :
                if done:
                    break
                sys.stdout.write('\rhacking in the bcone server for next colour--------- ' + c)
                sys.stdout.flush()
                time.sleep(0.1)
            sys.stdout.write('\rDone!     ')

        t = threading.Thread(target=animate)
        t.start()

        #long process here
        time.sleep(20)
        done = True

    def chalo1():
        done = False
        #here is the animation
        def animate():
            for c in itertools.cycle(['|', '/', '-', '\\']):
                if done:
                    break
                sys.stdout.write('\rgetting the colour wait --------- ' + c)
                sys.stdout.flush()
                time.sleep(0.1)
            sys.stdout.write('\rDone!     ')

        t = threading.Thread(target=animate)
        t.start()

        #long process here
        time.sleep(20)
        done = True

    def clear():
        # for windows
        if name == 'nt':
            _ = system('cls')
        # for mac and linux(here, os.name is 'posix')
        else:
            _ = system('clear')
    def getSum(n):
        sum=0
        for digit in str(n):
            sum+= int(digit)
        return sum
    def lawde_time_pe_khel(n):
        check=0
        for digit in (n):
            if(int(digit)==0):
                check=check+1
        return check
    clear()
    y=1
    newperiod=period
    banner='figlet RXCE'
    numbers=[]
    while(y):
        clear()
        system(banner)
        print("Contact me on telegram @ ProfessorMH09")
        print("Enter ",newperiod," Bcone Price :")
        current=input()
        current=int(current)
        chalo()
        print("\n---------Successfully hacked the server-----------")
        chalo1()
        print("\n---------Successfully got the colour -------------")
        print('\n')
        last2=str(current)[-2:]
        samjha_maadarchod=lawde_time_pe_khel(last2)
        if(newperiod%2==0):
            sum=getSum(current)+samjha_maadarchod
            if(sum%2==0):
                print(newperiod+1," : ðŸ”´")
            else:
                print(newperiod+1,"  : ðŸŸ¢")
        else:
            sum=getSum(current)+samjha_maadarchod+1
            if(sum%2==0):
                print(newperiod+1,"   : ðŸ”´")
            else:
                print(newperiod+1,"   : ðŸŸ¢")
        newperiod+=1
        numbers.append(current)
        y=input("Do you want to play : Press 1 and 0 to exit \n")
        if(y==0):
            y=False
        if (len(numbers)>11):
            clear()
            system('figlet Thank you!!')
            print("Play on next specified time!!")
            print("-----------Current Time UP----------")
            sys.exit(" \n \n \n Contact on Telegram ProfessorMH09")
            #print(numbers)
  
if(expirydate>today):
    now = datetime.datetime.now()
    First = now.replace(hour=13, minute=55, second=0, microsecond=0)
    Firstend = now.replace(hour=14, minute=35, second=0, microsecond=0)
    Second = now.replace(hour=16, minute=25, second=0, microsecond=0)
    Secondend = now.replace(hour=17, minute=35, second=0, microsecond=0)
    Third = now.replace(hour=15, minute=55, second=0, microsecond=0)
    Thirdend = now.replace(hour=16, minute=35, second=0, microsecond=0)
    Final = now.replace(hour=17, minute=55, second=0, microsecond=0)
    Finalend = now.replace(hour=18, minute=35, second=0, microsecond=0)
        #if (now>First and now<Firstend):
           #        period=220
           #        #hero()
          #if (now>Second and now<Secondend):
            #        period=240
            #        #hero()
           #if (now>Third and now<Thirdend):
             #        period=260
             #        #hero()
            #if (now>Fourth and now<Fourthend):
            #        period=280
            #        #hero()

    elif(now>Sixth and now<Sixthend):
            period=340
            hero()
elif(now>Seventh and now<Seventhend):
            period=340
            hero()
         elif(now>Eighth and now<Eigthend):
            period=380
            hero()
            elif(now>Ninth and now<Ninthend):
            period=420
            hero()
            elif(now>Tenth and now<Tenthend):
            period=440
            hero()
            elif(now>Final and now<Finalend):
            period=460
            hero()
    else:
        banner='figlet RXCE'
        system(banner)
        #print("Hi!! Thanks for buying the hack")
        print("Hi! thanks for trying our DEMO")
        print("----------Your play time-----------")
        #print("4st Oct 2021, 11:00 AM- 11:30 PM")
        #print("4st Oct 2021, 11:00 PM- 11:30 PM")
        print("31rd Oct 2021, 11:00 PM- 11:30 PM")
        #print("31st Oct 2021, 11:00 PM- 11:30 PM")
        print("Please play on the given time, and ")
        print("If you think it is an error contact")
        print(" admin on telegram @ProfessorMH09 ")


else:
    def clear():
        # for windows
        if name == 'nt':
            _ = system('cls')
        # for mac and linux(here, os.name is 'posix')
        else:
            _ = system('clear')
    code="PROFESSOR"
    nextday="THALA"
    nexday1="LEGEND"
    banner='figlet RXCE'
    system(banner)
    print("*---------*----------*-------------*----------*")
    print("Your hack has expired--- Please contact")
    print(" on telegram ----@ProfessorMH09 for activating")
    print(" Recharge Amount :        Total limit " )
    print(" 1.     500 INR -------  10 Day (pr day 30 Games")
    print(" 2.     1000 INR -------  30 Days( pr day 30 Games")
    print("*---------*----------*-------------*----------*")
    print("Your custom hack can be made request from us.")
    print("Beware of fraudsters!!!")
    while(True):
        print("My banking name is ProfessorMH09")
        print("If you send to any other name , then IT IS SCAMMM")
        print("--------*--------*----------*---------")
        print("send payment only to ProfessorMH09")
        print("If you have already paid to above UPI")
        print("Please Enter your 12 Digit \n UPI reference number ")
        print("or please Enter Correct activation code for 12:00 AM- 11:55 PM ")
        bhai=input(": ")
        if(bhai==code):
            clear()
            print("Your play time is Today, 4th Oct 2021")
            print("Only play on your given time:")
            time.sleep(20)
            period=490
            hero()
        elif(bhai==nextday or bhai==nexday1):
            clear()
            banner='figlet RXCE'
            system(banner)
            print("----------Your play time-----------")
           #print(playday," 11:00 AM- 11:30 AM")
           #print(playday," 12:00 AM- 12:30 PM")
           #print(playday," 01:00 PM- 01:30 PM")
           #print(playday," 02:00 PM- 02:30 PM")
           #print(playday," 03:00 PM- 03:30 PM")
           #print(playday," 05:00 AM- 05:30 PM")
           #print(playday," 06:00 AM- 06:30 PM")
           #print(playday," 07:00 AM- 07:30 PM")
           #print(playday," 09:00 AM- 09:30 PM")
           #print(playday," 10:00 AM- 10:30 PM")
           #print(playday," 11:00 AM- 11:30 PM")
            print("Please play on the given time, and ")
            print("If you think it is an error contact")
            #period=210
            sys.exit(" \n \n \n Contact on Telegram @ ProfessorMH09")
            
            
        else:
            clear()
            banner='figlet RXCE'
            system(banner)
            print("Incorrect Activation Code :")
     
